audit_header: false
title: The Emerald Coast Real Estate Video Blog with Scott Gregory
description: Our mission at The Scott Gregory Team is to be your best resource for The Emerald Coast real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Scott Gregory Team, your professional The Emerald Coast Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Scott Gregory
  title:
  license_number:
  about_markdown: |
    Scott Gregory is the lead agent on The Scott Gregory Team at eXp Realty, and has been a top producer in real estate sales along the Emerald Coast for the last two decades. Scott and his team specialize in residential sales and investment properties. When you buy or sell with Scott, you get a full team at your service. Scott also is a national real estate sales coach with Club Wealth real estate coaching. His team can help you buy or sell property anywhere in America. Referrals are always welcome. Interested in a career in real estate anywhere in America, or in opportunities with his team? Reach out to Scott.
    
        www.HomeSearchEmeraldCoast.com 
        www.GrittyAgents.com 
        www.JoinTheRealEstateRevolution.com 
        850-692-2292 (Call or Text)
  brand: The Scott Gregory Team
  brokerage: eXp Realty
  market: The Emerald Coast
  # address: 1776 Sea Lark Ln Suite 5<br>Navarre, FL 32566
  phone: 850-692-2292
  phone_type:
  phone2:
  phone2_type:
  email: scottgregoryteam@gmail.com
  url: http://www.homesearchemeraldcoast.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.homesearchemeraldcoast.com/homevalue/homeevaluation
  second_CTA_text: Home Search
  second_CTA_URL: https://www.homesearchemeraldcoast.com/search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your The Emerald Coast Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.homesearchemeraldcoast.com/homevalue/homeevaluation

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a The Emerald Coast Home?"
    CTA_text2: "Search the entire MLS for your The Emerald Coast home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.homesearchemeraldcoast.com/search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone: 850-692-2292
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/ScottGregoryTeamKellerWilliams/
  linkedin_url: https://www.linkedin.com/in/scottgregoryteam
  youtube_url:
  twitter_url: http://www.twitter.com/scottgregory850
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/TheScottGregoryTeam/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'The Emerald Coast Real Estate Podcast with Scott Gregory'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the The Emerald Coast Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Scott Gregory Team - your professional The Emerald Coast Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in The Emerald Coast, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Scott Gregory'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_logo2_path: /img/logo2.png
  logo_width_number: 40
  # hero_text: The Emerald Coast Real Estate Video Blog
  hero_background_hex: '#eee'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#19469d'
  accent_color: '#f5821f'
  theme_color: '#00021a'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
